# Налаштування підключення до PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

# Налаштування Hibernate
# update — автоматично створює або оновлює таблиці в БД
spring.jpa.hibernate.ddl-auto=update

# Відображення SQL запитів у консолі (корисно для відладки)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true